---
AWSTemplateFormatVersion: '2010-09-09'
Outputs:
  SkeletonVpcId:
    Value:
      Ref: SkeletonVpc
Resources:
  SkeletonVpc:
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
    Type: AWS::EC2::VPC
